package dot.empire.gol;

import javax.swing.*;
import java.awt.*;
import java.util.LinkedList;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;

/**
 * Main Frame. Created by siD at 09 Apr 2018 5:04:01 PM.
 *
 * @author siD
 */
public class FrameMain extends JFrame {

    LinkedList<Runnable> r = new LinkedList<>();

    private int size = 46;
    private JButton[][] arr;

    /**
     * Creates new form Main Frame.
     *
     * @param parent Parent frame
     */
    public FrameMain(Component parent) {
        super("~ Conway's Game of Life ~");
        this.initComponents();

        super.setLocationRelativeTo(parent);

        // --
        this.arr = new JButton[size][size];
        this.pnlMain.setLayout(new GridLayout(size, 0));
        for (int x = 0; x < size; x++) {
            for (int y = 0; y < size; y++) {
                JButton btn = new JButton();
                this.arr[x][y] = btn;
                this.pnlMain.add(btn);
            }
        }

        this.create();

        new Timer().scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                update();
            }
        }, 0, (long) (0.25 * 1000));
    }

    private void create() {
        Random rand = new Random();
        for (int x = 0; x < size; x++) {
            for (int y = 0; y < size; y++) {
                arr[x][y].setEnabled(rand.nextInt(10) == 0);
            }
        }
    }

    private boolean isAlone(int x, int y) {
        return getNumFriends(x, y) < 2;
    }

    private boolean isCrowded(int x, int y) {
        return getNumFriends(x, y) > 3;
    }

    private int getNumFriends(int x, int y) {
        int num = 0;

        //<editor-fold defaultstate="collapsed" desc="Cardinal">
        try {
            if (arr[x + 1][y].isEnabled()) {
                num++;
            }
        } catch (IndexOutOfBoundsException ignore) {
        }
        try {
            if (arr[x - 1][y].isEnabled()) {
                num++;
            }
        } catch (IndexOutOfBoundsException ignore) {
        }
        try {
            if (arr[x][y + 1].isEnabled()) {
                num++;
            }
        } catch (IndexOutOfBoundsException ignore) {
        }
        try {
            if (arr[x][y - 1].isEnabled()) {
                num++;
            }
        } catch (IndexOutOfBoundsException ignore) {
        }
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="comment">
        try {
            if (arr[x + 1][y + 1].isEnabled()) {
                num++;
            }
        } catch (IndexOutOfBoundsException ignore) {
        }
        try {
            if (arr[x - 1][y + 1].isEnabled()) {
                num++;
            }
        } catch (IndexOutOfBoundsException ignore) {
        }
        try {
            if (arr[x + 1][y - 1].isEnabled()) {
                num++;
            }
        } catch (IndexOutOfBoundsException ignore) {
        }
        try {
            if (arr[x - 1][y - 1].isEnabled()) {
                num++;
            }
        } catch (IndexOutOfBoundsException ignore) {
        }
        //</editor-fold>
        return num;
    }

    private boolean isAlive(int x, int y) {
        return this.arr[x][y].isEnabled();
    }

    private void die(int x, int y) {
        this.arr[x][y].setEnabled(false);
    }

    private void update() {
        for (int x = 0; x < size; x++) {
            for (int y = 0; y < size; y++) {
                if (isAlive(x, y)) {
                    if (isAlone(x, y) || isCrowded(x, y)) {
                        final int xPos = x;
                        final int yPos = y;

                        r.add(() -> {
                            die(xPos, yPos);
                        });
                    }
                } else if (getNumFriends(x, y) == 3) {

                    final int xPos = x;
                    final int yPos = y;

                    r.add(() -> {
                        arr[xPos][yPos].setEnabled(true);
                    });
                }
            }
        }

        for (Runnable evt : r) {
            evt.run();
        }
        r.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * <strong>WARNING: Do NOT modify this code.</strong> The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scollPane = new javax.swing.JScrollPane();
        pnlMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemRecreate = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1598, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );

        scollPane.setViewportView(pnlMain);

        jMenu1.setText("File");

        menuItemRecreate.setText("Recreate");
        menuItemRecreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRecreateActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRecreate);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scollPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRecreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRecreateActionPerformed
        this.create();
    }//GEN-LAST:event_menuItemRecreateActionPerformed

    //<editor-fold defaultstate="collapsed" desc="Generated Varibles">  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemRecreate;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane scollPane;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
